-d C:\Users\simto\OneDrive\Desktop\UART\uart_project\impl\gwsynthesis\uart_project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\simto\OneDrive\Desktop\UART\uart_project\src\uart_project.cst
-cfg C:\Users\simto\OneDrive\Desktop\UART\uart_project\impl\pnr\device.cfg
-sdc C:\Users\simto\OneDrive\Desktop\UART\uart_project\src\uart_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
